### PR TITLE
add cypress examples

### PR DESCRIPTION
**Pull request by eyaly**

### CODE REVIEW

**Review by nadvolod — CHANGES_REQUESTED** [review]
I’m not understanding why we need 3 extra files with 100s of LOCs just to show the difference between running by concurrency vs spec?

**Comment by wswebcreation** [comment]
> I’m not understanding why we need 3 extra files with 100s of LOCs just to show the difference between running by concurrency vs spec?

I'm don't understand why this is a problem. I've had multiple requests, including from you, to create multiple single folders with only one or 2 changes in the samples but adding 20 extra files in that folder 😆 

If we really want to prevent this that we should be more clear in or our docs on how to use this, or in the readme. These samples are created because our customers ask for them and they or haven't or wont read our docs where this is also explained.

**Comment by eyaly** [comment]
@nadvolod or @wswebcreation - Can we review and merge these examples for the main branch?

**Comment by nadvolod** [comment]
> > I’m not understanding why we need 3 extra files with 100s of LOCs just to show the difference between running by concurrency vs spec?
> 
> I'm don't understand why this is a problem. I've had multiple requests, including from you, to create multiple single folders with only one or 2 changes in the samples but adding 20 extra files in that folder 😆
> 
> If we really want to prevent this that we should be more clear in or our docs on how to use this, or in the readme. These samples are created because our customers ask for them and they or haven't or wont read our docs where this is also explained.

@wswebcreation it's a problem because any time any information needs to be update in a `.yml` file then we need to update 5 yml files! For example, when we change Cypress versions, now we need to change 5 ymls. When we update our yml to go from v9 to v10. Now we need to change 5 ymls again. If a capability gets outdated and no longer valid. And so on. Escpecially when we can choose to shard by spec or concurrency using command line.

About this "create multiple single folders with only one or 2 changes in the samples but adding 20 extra files in that folder". I think there was a miscommunication as I never asked for this. I wanted different examples to show off different features. This is valid as Eyal is trying to do here. The way that this was implemented wasn't ideal. Instead of having so many folders with so many files it should have been a single `package.json` that controls a library. Now add one new test file with the feature we want to show. Add a `script` to `package.json` to execute that specific feature. That would be a more maintainable implementation. We only need a single test case or a file to show off a different sauce feature. We don't need an entirely new directory as we currently have. 
We do the same thing in other programming languages. If you want a new feature, just write a single test. And that one test with an updated README is what typically gets checked in.

**Comment by nadvolod** [comment]
> @nadvolod or @wswebcreation - Can we review and merge these examples for the main branch?

@eyaly not yet. I don't understand why we need 5 yml files to show the difference between shard by concurrency vs. shard by spec. Can you please help me to understand?

**Comment by nadvolod** [comment]
> Hi @nadvolod
> 
> _I don't understand why we need 5 yml files to show the difference between shard by concurrency vs. shard by spec. Can you please help me to understand?_
> 
> This is a repo for a demo purpose, and for a demo, we need examples to show the features we have and when and why to use spec or concurrency. This repo is not mentioned in our docs. It is for us. And if we think we need more examples so let it be. If required, I have no problems "wasting" 20 min every year to amend 5 yml files instead of 2 ;-)

You don't want to take 30 seconds just to change 1 line of code from `shard: concurrency` to `shard: spec` manually in `config-ex2.yml`? 
The second problem is that this doesn't only impact you, it impacts everyone that uses this repo. So far, I've been the one that has had to update the `yml` files to match the new requirements. If you want to add more files for more examples, how can we ensure that you will keep them up to date?

**Comment by eyaly** [comment]
@nikolay-advolodkin 

The examples are not only about shard.
The examples cover: (1) run all specs on 1 chrome browser as it is done without Sauce (2) Split the specs to different chrome browsers, and run in parallel for fast feedback and result (3) Cross-browser tests (4) Cross-version tests (5) SC

 _If you want to add more files for more examples, how can we ensure that you will keep them up to date?_
The repos under saucelabs-training are the SA team's responsibility. 
Same as you add Visual tests to Java repo, Same as I amended the Java appium tests to use Java 1.8.2 and W3C, Same as Wim updates the WDIO examples -> This is part of our role.

**Pull request merged**
