### PR TITLE
Adding GH Actions for SauceCTL

### PR DESCRIPTION
**Pull request by johnorrsauce**
Adding new Github Action examples for SauceCTL with Cypress, Playwright, and TestCafe.

### CODE REVIEW

**Comment by wswebcreation** [comment]
@johnorrsauce and @joshmgrant 

thanks for this PR and merging it, can you raise a new PR to add badges to the readme with the status as with almost all the rest of the GH actions?

thanks

**Comment by johnorrsauce** [comment]
@wswebcreation, @joshmgrant 

I'll get these added in.

**Comment by johnorrsauce** [comment]
@wswebcreation, @joshmgrant 

I added in the three badges.  However, the other three Cypress bullets as linked  (examples 2-4) don't exist as noted in the specific Cypress [README](https://github.com/saucelabs-training/demo-js/blob/main/testrunner-toolkit/cypress/README.md).  And Example 5 is not noted.

**Comment by wswebcreation** [comment]
Hmm, we had multiple configs, @nikolay-advolodkin 

you’ve been playing with this lately, did you remove them?

**Comment by nikolay-advolodkin** [comment]
Hey Wim,
Yes, it was me.
There were several issues with having multiple configs
1. They were mostly redundant and didn't provide any extra value (I think
there's only a simple one and an advanced cross-platform one that's needed)
2. Any extra features that we want the tests to do can pretty much be
configured through CLI of saucectl in a script
3. Every time there was an API change or a bug to saucectl YML, we had to
update 5+ configs to make everything work. Having only 2 decreases the
level of effort. However, you will notice that we didn't lose any
functionality. We simply added new scripts to perform different operations.

*Nikolay Advolodkin*
Sr Solution Architect | Sauce Labs
Miami, FL
<https://twitter.com/Nikolay_A00>
<https://www.linkedin.com/in/nikolayadvolodkin/>
<https://saucelabs.com/digital-confidence?utm_source=email&utm_medium=BDR&utm_campaign=email&utm_term=emailsignature>
We're Hiring! <https://grnh.se/e14506051>

**Comment by wswebcreation** [comment]
Thanks for explaining @nikolay-advolodkin ,

Maybe for next time check if the files are referenced in the docs and remove that too 😉

**Comment by wswebcreation** [comment]
I've fixed the document issues

**Comment by nikolay-advolodkin** [comment]
Yea, you're right. I apologize for missing that.

*Nikolay Advolodkin*
Sr Solution Architect | Sauce Labs
Miami, FL
<https://twitter.com/Nikolay_A00>
<https://www.linkedin.com/in/nikolayadvolodkin/>
<https://saucelabs.com/digital-confidence?utm_source=email&utm_medium=BDR&utm_campaign=email&utm_term=emailsignature>
We're Hiring! <https://grnh.se/e14506051>

**Pull request merged**
